# site properties and page defaults
title: Intelligent Autonomy Lab
subtitle: A robotics, controls, and learning research lab at Yale University.
description: A robotics, controls, and learning lab located at Yale University.
header: images/robot-friends.jpg
footer: images/lab_img.png

# site social media and other links
links:
  email: ian.abraham@yale.edu
  orcid: 0000-0003-0299-1760
  google-scholar: URUPd4sAAAAJ
  github: ialab-yale
  twitter: ianabraha
  youtube: ymous

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
