# - id: doi:10.1371/journal.pcbi.1007128
#   type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review


- id: doi:10.15607/RSS.2023.XIX.082
  type: paper
  date: 2023-7-13
  description: In this paper, we investigate solutions to the time-optimal ergodic search problem for fast and adaptive robotic search and exploration.
  image: images/papers/time_opt_ergRSS23/fig1.png
  buttons: 
    - type: source
      text: Code 
      link: https://github.com/ialab-yale/time_optimal_ergodic_search
    - type: youtube
      text: RSS Talk
      link: live/ftQhK75Ri1E?feature=shared&t=17384
  tags:
    - time optimal
    - coverage
    - ergodicity
    - ergodic control 

- id: doi:10.1109/TRO.2022.3228130
  tags: 
    - Koopman operator theory
    - optimal control
    - learning

- id: doi:10.55417/fr.2023011
  tags:
    - multi-robot
    - ergodic control
    - ergodicitys
    - human-robot interaction

- id: doi:10.1109/TRO.2023.3284358
  tags: 
    - optimization 
    - multi-objective optimization
    - ergodic search
    - ergodicity